### ISSUE TITLE
Random number generators

### ISSUE THREAD

**Issue by waternumbers** [romanzenka/RUnit#4]
Currently the default random number generators in `defineTestSuite` and `runTestFile` - and possibly elsewhere, I've not looked - are currently set to
```
rngKind = "Marsaglia-Multicarry",
rngNormalKind = "Kinderman-Ramage"
```
In one of my packages this has resulted in warnings appearing all over the test suite. While the current options give some backward compatibility they have not been the R defaults for some time. Can you consider updating these to the R4.2.2 defaults of 
```
rngKind = "Mersenne-Twister",
rngNormalKind = "Inversion"
```

**Comment by romanzenka** [comment]
I will give that a shot in the next release. I believe that if someone needs a special RNG, they can override the defaults, otherwise it makes sense to use ones that are default to R.

**Comment by romanzenka** [comment]
@waternumbers I am a bit afraid of doing this. If I change this default setting, I will possibly change how unit tests work for literally every package that does not specify the random number generator, possibly breaking tests for everyone using RUnit. Since nobody else reported this issue, I think the safest way would be for you to override the defaults to what you want, and we leave the package as is. Would that be acceptable?

**Comment by waternumbers** [comment]
@romanzenka see your point, since I've been overriding the defaults since 2022 and the packages is on CRAN its fine by me.
